<?php
$this->headTitle('View Application');

$this->mainMenu()->setActiveItemId('applications');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Application'=>$this->url('applications'),
            'View Application'=>$this->url('applications', ['action'=>'view', 'id'=>$application->getId()])
            ]);
?>


<h1>View Application</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($application->getId()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($application->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?= $this->escapeHtml($application->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($application->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>