<?php
$this->headTitle('Configurations');

$this->mainMenu()->setActiveItemId('configurations');

$breadcrumbs = [
    'Home' => $this->url('home'),
    'Manage Configurations' => $this->url('configurations'),
];

$this->pageBreadcrumbs()->setItems($breadcrumbs);
?>

<h1>Manage Configurations</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<table class="table table-striped">

    <tr>
        <th>Key</th>
        <th>Value</th>
        <th>Actions</th>
    </tr>

    <?php /** @var \Configuration\Entity\ConfigurationGroup $childGroup */
    foreach ($configurationGroup->getChildGroups() as $childGroup): ?>
        <tr>
            <td><?= $this->escapeHtml($childGroup->getName()); ?></td>
            <td></td>
            <td>
                <nobr>
                    <a class="btn btn-info" href="<?= $this->url('configurations',
                        ['action' => 'list', 'id' => $childGroup->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil"></span> Manage
                    </a>
                </nobr>
            </td>
        </tr>
    <?php endforeach; ?>

    <?php /** @var \Configuration\Entity\Configuration $configuration */
    foreach ($configurationGroup->getConfigurations() as $configuration): ?>
        <tr>
            <td><?= $this->escapeHtml($configuration->getKey()); ?></td>
            <td><?= $this->escapeHtml($configuration->getValue()); ?></td>
            <td></td>
        </tr>
    <?php endforeach; ?>

</table>


