<?php
$this->headTitle('Edit Environment');

$this->mainMenu()->setActiveItemId('environments');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Environment'=>$this->url('environments'),
            'Edit Environment'=>$this->url('environments', ['action'=>'edit', 'id'=>$environment->getId()])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter name'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter description'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<h1>Edit Environment</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

