<?php
$this->headTitle('Environments');

$this->mainMenu()->setActiveItemId('environments');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Environments' => $this->url('environments'),
]);
?>

<h1>Manage Environments</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('environments', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Environment
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>

    <?php /** @var \Configuration\Entity\Environment $environment */
    foreach ($environments as $environment): ?>

        <tr>
            <td><?= $this->escapeHtml($environment->getId()); ?></td>
            <td>
                <a href="<?= $this->url('environments', ['action' => 'view', 'id' => $environment->getId()]); ?>">
                    <?= $this->escapeHtml($environment->getName()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($environment->getDescription()); ?></a>
            </td>
            <td>
                <nobr><?= $this->escapeHtml($environment->getDateCreated()); ?></nobr>
            </td>
            <td>
                <nobr>
                    <a class="btn btn-info" href="<?= $this->url('environments',
                        ['action' => 'edit', 'id' => $environment->getId()]); ?>">
                        <span class="glyphicon glyphicon-pencil"></span> Edit
                    </a>
                    <button type="button" class="btn btn-danger delete-record" data-toggle="modal" data-target="#deleteRecord"
                            data-id="<?= $this->escapeHtml($environment->getId()); ?>"
                    >
                        Delete
                    </button>
                </nobr>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

<div id="deleteRecord" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Do you really want to delete this environment?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger delete-record-confirm">Yes</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('.delete-record').click(function () {
        $('.delete-record-confirm').attr('href', '/environments/delete/' + $(this).data('id'))
    });
</script>
