<?php
$this->headTitle('View Environment');

$this->mainMenu()->setActiveItemId('environments');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Environment'=>$this->url('environments'),
            'View Environment'=>$this->url('environments', ['action'=>'view', 'id'=>$environment->getId()])
            ]);
?>


<h1>View Environment</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($environment->getId()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($environment->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?= $this->escapeHtml($environment->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($environment->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>