<?php
$this->headTitle('Roles');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Roles'=>$this->url('roles'),
            ]);
?>

<h1>Manage Roles</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="
    <?= $this->url('roles', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Role
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Date Created</th>
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($roles as $role): ?>
    
    <tr>
        <td><?= $this->escapeHtml($role->getId()); ?></td>
        <td>
            <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                <?= $this->escapeHtml($role->getName()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($role->getDescription()); ?></a> 
        </td>
        <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>        
        <td>
            </nobr>
            <a class="btn btn-info" href="<?= $this->url('roles', 
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <button type="button" class="btn btn-danger delete-record" data-toggle="modal" data-target="#deleteRecord"
                    data-id="<?= $this->escapeHtml($role->getId()); ?>"
            >
                Delete
            </button>
            </nobr>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<div id="deleteRecord" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Do you really want to delete this role?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger delete-record-confirm">Yes</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('.delete-record').click(function () {
        $('.delete-record-confirm').attr('href', '/roles/delete/' + $(this).data('id'))
    });
</script>


