<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome configuration management system</h1>

<p>Go to "Configuration management" to manage configurations of your applications</p>

<!--<p>-->
<!--    Click the <em>Sign in</em> button at the top right. To sign in, use the -->
<!--    following credentials:-->
<!--    <ul>-->
<!--        <li>Username: <em>admin@example.com</em></li>-->
<!--        <li>Password: <em>Secur1ty</em></li>-->
<!--    </ul>    -->
<!--</p>-->



